service: RestApi
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 2048
  stage: dev
  timeout: 20
  region: ap-south-1
  deploymentBucket:
    name: facebook-clone-api

functions:
  app-api:
    handler: build/server.handler
    events:
     - http: ANY /{proxy+}
     - http: ANY /
    environment:
        ENVIRONMENT: production
        DATABASE: mongodb://sohrab:facebook@ac-nmsfwa6-shard-00-00.feiggng.mongodb.net:27017,ac-nmsfwa6-shard-00-01.feiggng.mongodb.net:27017,ac-nmsfwa6-shard-00-02.feiggng.mongodb.net:27017/?ssl=true&replicaSet=atlas-7sm1d2-shard-0&authSource=admin&retryWrites=true&w=majority
        TOKEN_SECRET: 3xgDmbD8WC
        EMAIL: md.soharubhossen@gmail.com
        MAIL_PASSWORD: jzbqremfzvhnqnvx
        BUCKET_NAME: facebook-clone2
        BUCKET_REGION: ap-south-1
        AWS_USER_ACCESS_KEY: AKIAXGEMZLEC3URH2DF5
        AWS_USER_SECRET_ACCESS_KEY: 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