export const languageLinks = [
  { name: 'English (UK)', to: '/' },
  { name: 'Français (FR)', to: '/' },
  { name: 'العربية', to: '/' },
  { name: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', to: '/' },
  { name: 'Español (España)', to: '/' },
  { name: 'Italiano', to: '/' },
  { name: 'Deutsch', to: '/' },
  { name: 'Português (Brasil)', to: '/' },
  { name: 'हिन्दी', to: '/' },
  { name: '中文(简体)', to: '/' },
  { name: '日本語', to: '/' }
];

export const serviceLinks = [
  { name: 'Sign Up', to: '/' },
  { name: 'Log in', to: '/' },
  { name: 'Messenger', to: '/' },
  { name: 'Facebook Lite', to: '/' },
  { name: 'Watch', to: '/' },
  { name: 'Places', to: '/' },
  { name: 'Games', to: '/' },
  { name: 'Marketplace', to: '/' },
  { name: 'Facebook Pay', to: '/' },
  { name: 'Oculus', to: '/' },
  { name: 'Portal', to: '/' },
  { name: 'Instagram', to: '/' },
  { name: 'Bulletin', to: '/' },
  { name: 'Local', to: '/' },
  { name: 'Fundraisers', to: '/' },
  { name: 'Services', to: '/' },
  { name: 'Voting Information Centre', to: '/' },
  { name: 'Groups', to: '/' },
  { name: 'About', to: '/' },
  { name: 'Create ad', to: '/' },
  { name: 'Create Page', to: '/' },
  { name: 'Developers', to: '/' },
  { name: 'Careers', to: '/' },
  { name: 'Privacy', to: '/' },
  { name: 'Cookies', to: '/' },
  { name: 'AdChoices', to: '/', icon: 'adChoices_icon' },
  { name: 'Terms', to: '/' },
  { name: 'Help', to: '/' }
];
